#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Apr 17 20:56:26 2018

EWMA forecast of conditional volatility

@author: tianyulu
"""
a = 0.95
x_var = pd.ewma(x*x, com=1/a-1, adjust=False, ignore_na=True)


pd.ewma(arg, com=1/alpha-1, span=None, halflife=None, alpha=None, min_periods=20, freq=None, adjust=True, how=None, ignore_na=False)


import pandas as pd
import numpy as np
import numpy.testing.utils as NTU

nan = np.nan
x = pd.Series([nan, nan, nan, 13.109292, 12.623850, 12.150520])
x = pd.Series([12.6314, nan, 13.00234, 13.109292, 12.623850, 12.150520])
a = 0.95
z = pd.ewma(x*x, com=1/a-1, adjust=False, ignore_na=True)

def nanzero(x):
    return 0 if np.isnan(x) else x

x.ffill(inplace=True)
y = [x[0]*x[0]]
for xt in x[1:]:
    yt1 = y[-1]
    if np.isnan(yt1) and np.isnan(xt):
        yt = nan
    else:
        yt1 = nanzero(yt1)
        xt = nanzero(xt)
        #yt = a*yt1 + (1-a)*xt
        yt = (1-a)*yt1 + a*xt*xt
    y.append(yt)
y = pd.Series(y)

NTU.assert_allclose(y,z)

x = test_data

s = np.nanstd(x[0:19])


# sigma_t^2 = \sum_(i=0)^t(1-)